parameters:
    database_driver:   pdo_mysql
    database_host:     db-devel
    database_port:     3306
    database_name:     zim7
    database_user:     web_user_zim7
    database_password: aN8KxAkb

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret: 151ee3ded429d064d92cd46ea43f86d8b6c78d1c
    