zimt_web:
    resource: "@ZimtWebBundle/Controller/"
    type:     annotation
    prefix:   /

login_check:
  pattern: /user/loginCheck

logout:
  pattern: /user/logout

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
